### ISSUE TITLE
Firefox Extension links are no longer available

### ISSUE THREAD

**Issue by sideyourspirit** [OlivierLaflamme/Cheatsheet-God#21]
![image](https://user-images.githubusercontent.com/25956682/75991195-66ed1280-5ef6-11ea-8b81-17dd08a212e9.png)

**Comment by OlivierLaflamme** [comment]
Which plugin was this for? which links are affected?

**Comment by OlivierLaflamme** [comment]
ha

**Comment by OlivierLaflamme** [comment]
Turns out its all of them thanks for letting me know ill attempt to fix / update

**Comment by OlivierLaflamme** [comment]
Thank you mate much love <3 !! The issue has been fixed (checkout wappalyzer its my favorite plugin atm)
