### ISSUE TITLE
Password Cracking

### ISSUE THREAD

**Issue by susmithaaa** [OlivierLaflamme/Cheatsheet-God#4]
I see that there is no cheat sheet for Linux and Windows password cracking. Can I open a PR for it? @OlivierLaflamme

**Comment by OlivierLaflamme** [comment]
@susmithaaa go for it man! I do have passowrd attacks/ password base priv esc in both Cheatsheet_PenTesting.txt and Cheatsheet_LinuxPrivilegeEsc.txt. However I dont beleive I have a lot of Windows password cracking info. Feel free to follow "Cheatsheet_PenTesting.txt" format and append your contribution within the password attack section <3

**Comment by OlivierLaflamme** [comment]
@susmithaaa make sure you merge back to master when you're completed. I love that you've done so far! 👍
